### ISSUE TITLE
address search to replace mapzen

### ISSUE THREAD

**Issue by jgravois** [cityofsandiego/streetsSD#44]
hi there! let me know if you need a hand migrating off mapzen's [deprecated](https://mapzen.com/blog/migration/) search service.

I maintain a handy Esri [Leaflet control](https://github.com/Esri/esri-leaflet-geocoder) with really nice [TOU](https://github.com/Esri/esri-leaflet-geocoder#terms-and-conditions) that would be a cinch to plugin.

**Comment by MrMaksimize** [comment]
hey @jgravois that would actually be awesome.  I ended up hiding the geosearch in the last push so I could get some other stuff out faster.

Would love a PR!
